# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 49ed1a7ace623789786a5eb9142674f39430afc92939e2d163186f8192f83a05fc06e346b4db603fdbb220a76dc15511faeebc6cc7319fc057f138d0a2480a1b

test:
  secret_key_base: c3ab1dcac1c238f9f47d33be7f7f7ace3683c3af4170686669249267ae67f2d33c766311d3860e8e900b3b7ab914fb1b5433d0e086e27d388cedae552c1f9329

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
